### ISSUE TITLE
Crash with latest version

### ISSUE THREAD

**Issue by k1r0s** [Dumdidldum/DynamicTreesRoots#1]
Have u used the right versions to compile?

im using: [DynamicTrees-1.12.2-0.9.6.jar, Roots-1.12.2-3.0.21.jar]

and [mysticallib-1.12.2-1.4.0.jar] as a roots dep, maybe is that?
:\

full trace

```
[Server thread/ERROR] [FML]: An error occurred trying to load an 
EventBusSubscriber de.dumdidldum.dynamicTreesRoots.Content for modid 
dynamictreesroots java.lang.NoClassDefFoundError: 
epicsquid/mysticallib/event/RegisterContentEvent
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_231]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) 
~[?:1.8.0_231]
	at java.lang.Class.privateGetPublicMethods(Class.java:2902) 
~[?:1.8.0_231]
	at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_231]
	at 
net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82) 
~[EventBus.class:?]

... 32 more Caused by: java.lang.ClassNotFoundException: 
epicsquid.mysticallib.event.RegisterContentEvent
	at 
net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) 
~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) 
~[?:1.8.0_231]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) 
~[?:1.8.0_231]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_231]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) 
~[?:1.8.0_231]
	at java.lang.Class.privateGetPublicMethods(Class.java:2902) 
~[?:1.8.0_231]

```

**Comment by k1r0s** [comment]
could you please state which mysticlib version do you use?

https://github.com/Dumdidldum/DynamicTreesRoots/blob/master/src/main/java/de/dumdidldum/dynamicTreesRoots/Content.java#L27

**Comment by Dumdidldum** [comment]
Hello
Thanks for the heads up!
I have fixed it in the newest build.
I don't know why it worked in dev-env...
EDIT: i have used "mysticallib-1.12.2-1.4.0" to compile, so it should have worked
